//Authen
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

//Employee
export const FETCH_EMPLOYEES_REQUEST = 'FETCH_EMPLOYEES_REQUEST';
export const FETCH_EMPLOYEES_SUCCESS = 'FETCH_EMPLOYEES_SUCCESS';
export const FETCH_EMPLOYEES_FAILURE = 'FETCH_EMPLOYEES_FAILURE';
export const EDIT_EMPLOYEE_SUCCESS = "EDIT_EMPLOYEE_SUCCESS";
export const EDIT_EMPLOYEE_FAILURE  = "EDIT_EMPLOYEE_FAILURE";
export const ADD_EMPLOYEE_SUCCESS = 'ADD_EMPLOYEE_SUCCESS';
export const ADD_EMPLOYEE_FAILURE = 'ADD_EMPLOYEE_FAILURE';
export const UPDATE_EMPLOYEE_STATUS_SUCCESS = "UPDATE_EMPLOYEE_STATUS_SUCCESS" 
export const UPDATE_EMPLOYEE_STATUS_FAILURE = "UPDATE_EMPLOYEE_STATUS_FAILURE"

//Invoice
export const FETCH_INVOICES_REQUEST = 'FETCH_INVOICES_REQUEST';
export const FETCH_INVOICES_SUCCESS = 'FETCH_INVOICES_SUCCESS';
export const FETCH_INVOICES_FAILURE = 'FETCH_INVOICES_FAILURE';

//Movie
export const FETCH_MOVIES_REQUEST = "FETCH_MOVIES_REQUEST"
export const FETCH_MOVIES_SUCCESS = "FETCH_MOVIES_SUCCESS"
export const FETCH_MOVIES_FAILURE = "FETCH_MOVIES_FAILURE"
export const EDIT_MOVIES_SUCCESS  = "EDIT_MOVIES_SUCCESS";
export const EDIT_MOVIES_FAILURE  = "EDIT_MOVIES_FAILURE";
export const ADD_MOVIES_SUCCESS  = "ADD_MOVIES_SUCCESS";
export const ADD_MOVIES_FAILURE  = "ADD_MOVIES_FAILURE";

//Room
export const FETCH_ROOMS_REQUEST = "FETCH_ROOMS_REQUEST"
export const FETCH_ROOMS_SUCCESS = "FETCH_ROOMS_SUCCESS"
export const FETCH_ROOMS_FAILURE = "FETCH_ROOMS_FAILURE"
export const EDIT_ROOMS_SUCCESS = "EDIT_ROOMS_SUCCESS"
export const EDIT_ROOMS_FAILURE = "EDIT_ROOMS_FAILURE"
export const ADD_ROOMS_SUCCESS = "ADD_ROOMS_SUCCESS"
export const ADD_ROOMS_FAILURE = "ADD_ROOMS_FAILURE"

//Seat
export const FETCH_SEATS_REQUEST = "FETCH_SEATS_REQUEST"
export const FETCH_SEATS_SUCCESS = "FETCH_SEATS_SUCCESS"
export const FETCH_SEATS_FAILURE = "FETCH_SEATS_FAILURE"
export const ADD_SEATS_SUCCESS = "ADD_SEATS_SUCCESS"
export const ADD_SEATS_FAILURE = "ADD_SEATS_FAILURE"